apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-control-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: satya03521/stress-control-core
        ports:
        - containerPort: 4000