name: Build and Deploy to Localhost

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load bash profile and use Node v20.11.0
        run: |
          source ~/.bash_profile
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use v20.11.0
          node -v
          npm -v

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Start Services with PM2
        run: |
          pm2 delete all || true
          pm2 start backend/pm2.config.js
          pm2 start frontend/pm2.config.js
          pm2 save

      - name: Show PM2 Status
        run: pm2 status